import type Phaser from 'phaser';

const toHex = (color: number): string => `#${color.toString(16).padStart(6, '0')}`;

export const UI_THEME = {
    palette: {
        backdropDeep: 0x111827,
        backdropMid: 0x1f2937,
        surfaceBase: 0x243447,
        surfaceMuted: 0x1e2d3f,
        surfaceRaised: 0x2a4057,
        tileIdle: 0x2a4057,
        tileHover: 0x35506b,
        tileSelected: 0xff5d5d,
        textStrong: 0xf9fafb,
        textBody: 0xe5e7eb,
        textMuted: 0x9ca3af,
        accent: 0xff5d5d,
        accentAlt: 0x38bdf8,
        success: 0x22c55e,
        danger: 0xef4444,
        timerLow: 0xef4444,
        borderStrong: 0x4b647d,
        borderSoft: 0x3c5168,
    },
    typeScale: {
        title: 34,
        timer: 34,
        metric: 17,
        currentWord: 30,
        body: 14,
        label: 13,
        button: 16,
        tileLetter: 24,
    },
    spacing: {
        xs: 6,
        sm: 10,
        md: 16,
        lg: 24,
        xl: 32,
    },
    radii: {
        panel: 14,
        button: 12,
        tile: 10,
    },
    emphasis: {
        borderWidth: 2,
        panelAlpha: 0.92,
        pathAlpha: 0.72,
        hoverLighten: 18,
        pressDarken: 14,
        disabledAlpha: 0.38,
    },
    tuning: {
        wordHistoryLimit: 8,
        growthFadeInMs: 260,
        feedbackDurationMs: 1600,
        expansionMotion: {
            tilePunchScale: 1.09,
            tilePunchMs: 120,
            flashAlpha: 0.5,
            flashInMs: 60,
            flashOutMs: 170,
            burstParticles: 10,
            burstDistance: 62,
            burstMs: 260,
            particleSizeMin: 4,
            particleSizeMax: 9,
            cameraShakeMs: 110,
            cameraShakeIntensity: 0.003,
            inputLockMs: 180,
        },
    },
    font: {
        display: 'Bungee, ui-sans-serif, sans-serif',
        body: 'Barlow, ui-sans-serif, sans-serif',
        mono: 'Space Mono, ui-monospace, SFMono-Regular, monospace',
    },
} as const;

export const uiTextStyles = {
    title: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.title}px`,
        fontFamily: UI_THEME.font.display,
        color: toHex(UI_THEME.palette.accent),
        stroke: toHex(UI_THEME.palette.backdropDeep),
        strokeThickness: 4,
        resolution: 2,
    }),
    timer: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.timer}px`,
        fontFamily: UI_THEME.font.mono,
        fontStyle: 'bold',
        color: toHex(UI_THEME.palette.textStrong),
        resolution: 2,
    }),
    metric: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.metric}px`,
        fontFamily: UI_THEME.font.mono,
        fontStyle: 'bold',
        color: toHex(UI_THEME.palette.textBody),
        resolution: 2,
    }),
    currentWord: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.currentWord}px`,
        fontFamily: UI_THEME.font.display,
        color: toHex(UI_THEME.palette.textStrong),
        letterSpacing: 4,
        stroke: toHex(UI_THEME.palette.backdropDeep),
        strokeThickness: 3,
        resolution: 2,
    }),
    feedback: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.metric}px`,
        fontFamily: UI_THEME.font.body,
        fontStyle: 'bold',
        color: toHex(UI_THEME.palette.success),
        resolution: 2,
    }),
    label: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.label}px`,
        fontFamily: UI_THEME.font.body,
        fontStyle: 'bold',
        color: toHex(UI_THEME.palette.textMuted),
        resolution: 2,
    }),
    body: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.body}px`,
        fontFamily: UI_THEME.font.mono,
        color: toHex(UI_THEME.palette.textBody),
        resolution: 2,
    }),
    button: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.button}px`,
        fontFamily: UI_THEME.font.body,
        fontStyle: 'bold',
        color: toHex(UI_THEME.palette.textStrong),
        resolution: 2,
    }),
    tileLetter: (): Phaser.Types.GameObjects.Text.TextStyle => ({
        fontSize: `${UI_THEME.typeScale.tileLetter}px`,
        fontFamily: UI_THEME.font.display,
        color: toHex(UI_THEME.palette.textStrong),
        stroke: toHex(UI_THEME.palette.backdropDeep),
        strokeThickness: 2,
        resolution: 2,
    }),
};

export const themeColorHex = toHex;